// Run with NODE_PATH pointing to a test-only installation of @electric-sql/pglite.
const {PGlite}=require('@electric-sql/pglite');const fs=require('fs');const assert=require('assert/strict');
(async()=>{const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);await db.exec(fs.readFileSync('supabase/migrations/202609150001_membership.sql','utf8'));
const a='00000000-0000-0000-0000-000000000001',u='00000000-0000-0000-0000-000000000002',v='00000000-0000-0000-0000-000000000003';await db.exec(`insert into auth.users values('${a}'),('${u}'),('${v}');insert into bgm_private.admins values('${a}');`);
const as=async(id,role='authenticated')=>db.exec(`reset role;set role ${role};select set_config('request.jwt.claim.sub','${id}',false)`);
const q=async(s,args=[])=> (await db.query(s,args)).rows;
const fails=async fn=>{let bad=false;try{await fn();}catch{bad=true;}assert(bad,'Expected rejection');};
await as(u);await fails(()=>q("select public.bgm_create_order('monthly')"));await fails(()=>q("insert into public.bgm_memberships values($1,now()+interval '1 year')",[u]));await fails(()=>q("select public.bgm_save_article('test','Title','A public preview',repeat('secret',20),true)"));
await as(a);const [{id}]=await q("select public.bgm_save_article('test','Title','A public preview',repeat('secret',20),true) as id");await db.exec('reset role;update public.bgm_settings set enrollment_open=true;');await as(u);assert.equal((await q('select * from public.bgm_article_bodies')).length,0);
const [{o}]=await q("select to_json(public.bgm_create_order('monthly')) as o");assert.equal(o.amount,29);const same=await q("select to_json(public.bgm_create_order('monthly')) as o");assert.equal(same[0].o.id,o.id);
await as(v);assert.equal((await q('select * from public.bgm_orders')).length,0);await fails(()=>q('select public.bgm_submit_tx($1,$2)',[o.id,'a'.repeat(64)]));await as(u);await q('select public.bgm_submit_tx($1,$2)',[o.id,'a'.repeat(64)]);await fails(()=>q('select public.bgm_review_order($1,true,$2)',[o.id,'verified']));
await as(a);await q('select public.bgm_review_order($1,true,$2)',[o.id,'verified exact USDT receipt']);await fails(()=>q('select public.bgm_review_order($1,true,$2)',[o.id,'duplicate review']));await as(u);assert.equal((await q('select * from public.bgm_article_bodies')).length,1);const exp=(await q('select expires_at from public.bgm_memberships'))[0].expires_at;
const annual=(await q("select to_json(public.bgm_create_order('annual')) as o"))[0].o;await fails(()=>q('select public.bgm_submit_tx($1,$2)',[annual.id,'a'.repeat(64)]));await q('select public.bgm_submit_tx($1,$2)',[annual.id,'b'.repeat(64)]);await as(a);await q('select public.bgm_review_order($1,true,$2)',[annual.id,'verified renewal receipt']);await as(u);assert(Date.parse((await q('select expires_at from public.bgm_memberships'))[0].expires_at)>Date.parse(exp)+360*86400000);
await db.exec(`reset role;update public.bgm_memberships set expires_at=now()-interval '1 second';`);await as(u);assert.equal((await q('select * from public.bgm_article_bodies')).length,0);
await as('', 'anon');assert.equal((await q('select * from public.bgm_articles')).length,1);await fails(()=>q('select * from public.bgm_article_bodies'));await fails(()=>q('select * from public.bgm_orders'));
console.log('PASS: closed enrollment, protected content, expiry, owner-only orders, admin-only approval, duplicate transaction/review rejection and renewal extension.');await db.close();})().catch(e=>{console.error(e);process.exit(1)});
