// Browser contract checks with a mocked Supabase API; not a live-service acceptance test.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/google-analytics|googletagmanager/,r=>r.abort());
const uid='00000000-0000-0000-0000-000000000002',oid='00000000-0000-0000-0000-000000000010',aid='00000000-0000-0000-0000-000000000020';let admin=false,tx=false,approved=false,saved=false;
const user={id:uid,email:'member@example.com',aud:'authenticated',role:'authenticated',created_at:new Date().toISOString()};const payload=Buffer.from(JSON.stringify({sub:uid,exp:Math.floor(Date.now()/1000)+3600,role:'authenticated'})).toString('base64url');const session={access_token:'eyJhbGciOiJIUzI1NiJ9.'+payload+'.test',refresh_token:'test-refresh',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user};
await page.route('**/assets/member-config.json',r=>r.fulfill({json:{supabaseUrl:'https://test.supabase.co',publishableKey:'sb_publishable_test'}}));
await page.route('https://test.supabase.co/**',async r=>{const u=new URL(r.request().url()),path=u.pathname;const body=r.request().postDataJSON();let data=[];
if(path==='/auth/v1/token')data=session;else if(path==='/auth/v1/user')data=user;
else if(path.endsWith('/bgm_settings'))data={enrollment_open:true};
else if(path.endsWith('/rpc/bgm_is_admin'))data=admin;
else if(path.endsWith('/bgm_memberships'))data=[{expires_at:new Date(Date.now()+86400000).toISOString()}];
else if(path.endsWith('/bgm_orders'))data=admin?[{id:oid,user_id:uid,plan:'monthly',amount:29,wallet:'test-wallet',txid:'a'.repeat(64),status:'pending'}]:[];
else if(path.endsWith('/rpc/bgm_create_order')){assert.equal(body.p_plan,'annual');data={id:oid,plan:'annual',amount:204,wallet:'test-wallet',status:'awaiting_payment'};}
else if(path.endsWith('/rpc/bgm_submit_tx')){assert.equal(body.p_order,oid);assert.equal(body.p_txid,'a'.repeat(64));tx=true;data=null;}
else if(path.endsWith('/rpc/bgm_review_order')){assert.equal(body.p_approve,true);approved=true;data=null;}
else if(path.endsWith('/rpc/bgm_save_article')){assert.equal(body.p_slug,'test-guide');saved=true;data=aid;}
else if(path.endsWith('/bgm_articles'))data=[{id:aid,slug:'test-guide',title:'Test guide',preview:'Public preview',published:true}];
else if(path.endsWith('/bgm_article_bodies'))data=[{body:'Private content <img src=x onerror="window.XSS=true">'}];
if(path.endsWith('/bgm_orders')&&u.searchParams.get('id'))data={id:oid,plan:'annual',amount:204,wallet:'test-wallet',status:'awaiting_payment'};
await r.fulfill({json:data});});
await page.goto('http://localhost:8765/account/');await page.locator('#auth-box').waitFor({state:'visible'});await page.locator('[name=email]').fill('member@example.com');await page.locator('#auth-form [name=password]').fill('testpass123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.locator('#account-box').waitFor({state:'visible'});
await page.goto('http://localhost:8765/membership/checkout/');await page.locator('#checkout-box').waitFor({state:'visible'});await page.selectOption('[name=plan]','annual');await page.getByRole('button',{name:'Create payment request'}).click();await page.locator('#payment-instructions').waitFor({state:'visible'});assert((await page.locator('#order-details').innerText()).includes('204'));await page.fill('[name=txid]','a'.repeat(64));await page.getByRole('button',{name:'Submit for verification'}).click();await page.waitForFunction(()=>document.getElementById('member-status').textContent.includes('Transaction submitted'));assert(tx);
await page.goto('http://localhost:8765/analysis/members/');await page.getByRole('button',{name:'Read full article'}).click();await page.locator('#premium-reader').waitFor({state:'visible'});assert.equal(await page.locator('#premium-reader img').count(),0);assert.equal(await page.evaluate(()=>window.XSS),undefined);
admin=true;await page.goto('http://localhost:8765/membership/admin/');await page.locator('#admin-box').waitFor({state:'visible'});await page.fill('[name=note]','Verified full USDT transfer');await page.check('[name=verified]');await page.getByRole('button',{name:'Approve and activate'}).click();await page.waitForFunction(()=>document.getElementById('member-status').textContent.includes('Payment approved'));assert(approved);
await page.fill('[name=slug]','test-guide');await page.fill('[name=title]','Original analysis guide');await page.fill('[name=preview]','Public article preview');await page.fill('[name=body]','Original private guide content. '.repeat(5));await page.getByRole('button',{name:'Save article',exact:true}).click();await page.waitForFunction(()=>document.getElementById('member-status').textContent==='Article saved.');assert(saved);assert.deepEqual(errors,[]);console.log('PASS mocked UI: login, annual order, transaction submission, safe article rendering, admin review and publishing.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
