#!/usr/bin/env python3
"""Build BGM-owned free resources. Never rewrites individual journal articles."""
from pathlib import Path
import re, json, html, unicodedata
from collections import OrderedDict
ROOT=Path(__file__).resolve().parents[1]
def slug(s): return re.sub(r'[^a-z0-9]+','-',unicodedata.normalize('NFKD',s).encode('ascii','ignore').decode().lower()).strip('-')
def esc(s): return html.escape(str(s),quote=True)
def write(path,s):
 p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s)
head=(ROOT/'scripts/templates/head.html').read_text()
gate=(ROOT/'scripts/templates/tail.html').read_text()
nav='''<a class="skip" href="#main">Skip to content</a>
<header class="site-header"><div class="shell masthead"><a class="brand" href="/">BLACK<span>·</span>GOLD <small>MARKET</small></a><div class="mast-actions"><a href="/account/">Sign in</a><a href="/my-learning/">My learning</a><a class="button" href="/blueprint/">Free blueprint</a></div></div>
<nav class="shell site-nav expanded-nav" aria-label="Main navigation"><a href="/">Home</a>'''
menus=[('Learn',[('/learn/','Gold learning path'),('/learn/forex/','Forex academy'),('/learn/crypto/','Crypto academy'),('/glossary/','Trading glossary'),('/quizzes/','Quizzes')]),('Markets',[('/markets/','Market overview'),('/markets/forex/','Forex heatmap & screener'),('/markets/crypto/','Crypto overview'),('/markets/strength/','Currency strength')]),('Trading',[('/trading/','Trading library'),('/trading/technical-analysis/','Technical analysis'),('/trading/psychology/','Psychology'),('/trading/systems/','Trading systems'),('/trading/trade-ideas/','Trade ideas')]),('Tools',[('/tools/','All calculators'),('/tools/market-hours/','Market hours'),('/tools/currency-converter/','Currency converter'),('/tools/correlation/','Correlation'),('/tools/trade-journal/','Practice journal')])]
for title,links in menus:
 nav+=f'<details class="nav-group"><summary>{title}</summary><div class="nav-panel">'+''.join(f'<a href="{u}">{t}</a>' for u,t in links)+'</div></details>'
nav+='''<a class="nav-analysis" href="/analysis/"><span class="nav-premium-badge">◇ PREMIUM</span>Analysis</a><a href="/news/">News</a><a href="/economic-calendar/">Calendar</a><a href="/community/">Community</a></nav></header>'''
footer='''<footer class="site-footer"><div class="shell"><a class="brand" href="/">BLACK<span>·</span>GOLD <small>MARKET</small></a><p>Protect. Master. Grow. Learn the market. Build your process.</p><div class="footer-grid">'''
for title,links in [('Learn',menus[0][1]),('Explore',[('/analysis/','Analysis'),('/premium/','Premium packages'),('/journal/','All articles'),('/markets/','Market overview'),('/news/','Market news'),('/economic-calendar/','Economic calendar'),('/tools/','Trading tools')]),('Black Gold Market',[('/about.html','About Raphael'),('/contact/','Contact'),('/faq/','FAQ'),('/blueprint/','Newsletter & Blueprint'),('/community/','Community'),('/partners/','Partnership enquiries')]),('Resources',[('/tools/regulators/','Regulator directory'),('/privacy/','Privacy & data'),('/risk-disclosure/','Risk disclosure'),('/site-map/','Site directory'),('/vip/','The Trader’s Kit')])]:
 footer+='<div><h2>'+title+'</h2>'+''.join(f'<a href="{u}">{t}</a>' for u,t in links)+'</div>'
footer+='''</div><p class="disclaimer">Educational content only, not financial advice. Trading gold, FX, crypto and leveraged products involves substantial risk. No profit is promised. Market displays may be delayed or unavailable; check execution prices with your provider.</p><p class="meta">© 2026 Black Gold Market.</p></div></footer>'''
routes={}
def page(path,title,desc,body,scripts=''):
 h=re.sub(r'<title>.*?</title>',f'<title>{esc(title)} | Black Gold Market</title>',head,flags=re.S)
 for key in ['name="description"','property="og:description"']:
  h=re.sub(r'<meta '+key+r'[^>]*>',f'<meta {key} content="{esc(desc)}">',h)
 h=re.sub(r'<meta property="og:title"[^>]*>',f'<meta property="og:title" content="{esc(title)} | Black Gold Market">',h)
 h=re.sub(r'<meta property="og:url"[^>]*>',f'<meta property="og:url" content="https://blackgoldmarket.us{path}">',h)
 h=re.sub(r'<link rel="canonical"[^>]*>',f'<link rel="canonical" href="https://blackgoldmarket.us{path}">',h)
 if '/assets/premium.css' not in h:h+='\n<link rel="stylesheet" href="/assets/premium.css">'
 if '/assets/academy.css' not in h:h+='\n<link rel="stylesheet" href="/assets/academy.css">'
 eyebrow='MEMBERSHIP' if path.startswith(('/premium/','/membership/','/account/','/analysis/members/')) else 'FREE RESOURCES'
 h+='\n</head><body>'+nav+f'<main id="main" class="shell page"><p class="eyebrow">BLACK GOLD MARKET / {eyebrow}</p><h1>{esc(title)}</h1><p class="standfirst">{esc(desc)}</p>'+body+'</main>'+footer+'<script defer src="/assets/portal.js"></script><script defer src="/assets/tool-math.js"></script><script defer src="/assets/academy.js"></script>'+scripts+gate
 write(path.strip('/')+'/index.html',h)
 routes[path]=title

def cards(items):
 return '<div class="resource-grid">'+''.join(f'<a class="resource-card" href="{u}"><span class="eyebrow">{esc(k)}</span><h2>{esc(t)}</h2><p>{esc(d)}</p><strong>Explore →</strong></a>' for u,k,t,d in items)+'</div>'

lessons=[]
for line in (ROOT/'content/academy.tsv').read_text().splitlines():
 course,module,title,body,example,exercise,mistake=line.split('|')
 lessons.append(dict(course=course,module=module,title=title,body=body,example=example,exercise=exercise,mistake=mistake,id=slug(title),url='/learn/'+course+'/'+slug(title)+'/'))
for course,label in [('forex','Forex'),('crypto','Crypto')]:
 selected=[x for x in lessons if x['course']==course]
 groups=OrderedDict()
 for l in selected:groups.setdefault(l['module'],[]).append(l)
 intro=f'<div class="notice"><strong>{len(groups)} modules · {len(selected)} lessons · Free access</strong><p>Completion is saved only in this browser. It is a study record, not a qualification or a measure of trading readiness.</p><a href="/my-learning/">View your learning progress →</a></div>'
 for i,(m,ls) in enumerate(groups.items()):
  intro+=f'<section class="module"><div><p class="eyebrow">MODULE {i+1:02}</p><h2>{esc(m)}</h2></div><ol>'+''.join(f'<li><a href="{x["url"]}">{esc(x["title"])}<span data-lesson-status="{x["id"]}">Read →</span></a></li>' for x in ls)+'</ol></section>'
 intro+=f'<p><a class="button" href="/quizzes/{course}/">Try the {label.lower()} quiz</a> <a class="button secondary" href="/glossary/?topic={course}">Open glossary</a></p>'
 page('/learn/'+course+'/',label+' academy','Build a practical foundation with short lessons, worked examples and exercises. All examples are hypothetical.',intro)
 for i,l in enumerate(selected):
  longform=ROOT/('content/lessons/'+l['id']+'.html')
  if longform.exists():
   core='<p class="eyebrow">'+esc(l['module'])+'</p>'+longform.read_text().strip()
  else:
   core='<p class="eyebrow">'+esc(l['module'])+'</p><h2>The idea</h2><p>'+esc(l['body'])+'</p><section class="worked"><h2>A worked example</h2><p>'+esc(l['example'])+'</p></section><h2>Try it yourself</h2><p>'+esc(l['exercise'])+'</p><h2>A mistake to avoid</h2><p>'+esc(l['mistake'])+'</p>'
  body='<div class="lesson-layout"><article class="lesson-body">'+core+'<div class="completion"><button class="button" data-complete="'+l['id']+'" aria-pressed="false">Mark lesson complete</button><p class="meta" data-save-status>Saved on this browser only.</p></div><nav class="lesson-pagination" aria-label="Lesson navigation">'
  body+=(f'<a href="{selected[i-1]["url"]}">← Previous lesson</a>' if i else '<span></span>')+(f'<a href="{selected[i+1]["url"]}">Next lesson →</a>' if i<len(selected)-1 else f'<a href="/quizzes/{course}/">Take the quiz →</a>')+'</nav></article><aside class="lesson-aside"><h2>Keep learning</h2><a href="/learn/'+course+'/">Course outline</a><a href="/glossary/">Look up a term</a><a href="/tools/">Try a calculator</a><a href="/my-learning/">Your progress</a><p class="meta">Original Black Gold Market educational notes. Examples exclude costs unless stated.</p></aside></div>'
  page(l['url'],l['title'],f'{label} academy · {l["module"]}',body)
# Enrich existing gold path without replacing its original selected lessons.
gold=(ROOT/'learn/index.html').read_text()
if '<!-- academy-paths -->' not in gold:
 gold=gold.replace('</main>','<!-- academy-paths -->'+cards([('/learn/forex/','FOREX','Go deeper into FX','11 modules covering mechanics, charts, macro, risk and due diligence.'),('/learn/crypto/','CRYPTO','Understand digital assets','Foundations, custody, market mechanics and security.'),('/quizzes/','PRACTICE','Check your understanding','Get immediate feedback and explanations.')])+'</main>')
 write('learn/index.html',gold)
write('assets/lesson-catalog.json',json.dumps([{'id':l['id'],'title':l['title'],'course':l['course'],'url':l['url']} for l in lessons],indent=2))
page('/my-learning/','My learning','Track completed lessons on this browser. No account is created and progress does not sync across devices.','<div id="learning-progress" aria-live="polite">Loading your progress…</div><noscript><p>Enable JavaScript to view browser-local progress. All lessons remain accessible from the academy.</p></noscript><p><button class="button secondary" id="export-progress">Download progress backup</button></p><label>Restore a progress backup<input type="file" id="import-progress" accept="application/json,.json"></label><p id="progress-status" role="status"></p>'+cards([('/learn/forex/','33 LESSONS','Forex academy','Start with quotes and build towards a repeatable practice routine.'),('/learn/crypto/','12 LESSONS','Crypto academy','Understand networks, custody, derivatives and common risks.')]))
terms=[line.split('|') for line in (ROOT/'content/glossary.tsv').read_text().splitlines()]
body='<div class="library-controls"><label>Find a term<input id="term-search" type="search" placeholder="Try margin, pip or wallet"></label><label>Topic<select id="term-topic"><option value="all">All topics</option>'+''.join(f'<option value="{t}">{t.title()}</option>' for t in ['forex','gold','markets','risk','crypto'])+'</select></label><p id="term-count" role="status"></p></div><nav class="alphabet" aria-label="Browse glossary letters">'+''.join(f'<a href="#letter-{c}">{c}</a>' for c in sorted(set(t[0][0].upper() for t in terms)))+'</nav><div id="glossary-list">'
last=None
for term,topic,definition in sorted(terms):
 initial=term[0].upper()
 if initial!=last:body+=f'<h2 class="letter" id="letter-{initial}">{initial}</h2>';last=initial
 body+=f'<article class="term" data-topic="{topic}" id="{slug(term)}"><h3>{esc(term)}</h3><p>{esc(definition)}</p><a class="meta" href="#{slug(term)}">Link to this term</a></article>'
body+='</div>'
page('/glossary/','Trading glossary',f'{len(terms)} plain-language definitions for forex, gold, risk and crypto. Search by term or browse by topic.',body)
quizzes=json.loads((ROOT/'content/quizzes.json').read_text())
page('/quizzes/','Test your understanding','Four quizzes with explanations after every submission. Scores are for learning, not trading certification.',cards([(f'/quizzes/{k}/','8 QUESTIONS',v['title'],'Check the reasoning, review mistakes and try again.') for k,v in quizzes.items()]))
for k,v in quizzes.items():
 body='<form class="quiz-form" data-quiz="'+k+'">'
 for i,(q,options,answer,explanation) in enumerate(v['questions']):
  body+=f'<fieldset><legend>{i+1}. {esc(q)}</legend>'+''.join(f'<label class="choice"><input type="radio" name="q{i}" value="{j}" required> <span>{esc(o)}</span></label>' for j,o in enumerate(options))+f'<p class="quiz-feedback" data-answer="{answer}" data-explanation="{esc(explanation)}" hidden></p></fieldset>'
 body+='<button class="button" type="submit">Check my answers</button> <button class="button secondary" type="reset">Try again</button><p class="quiz-score" role="status"></p></form>'
 page('/quizzes/'+k+'/',v['title']+' quiz','Answer all eight questions to see your score and the explanation for each answer.',body)
# Calculators: original gold calculator keeps its formulas and gets a stable detail route.
goldtool=ROOT/'tools/gold-position-size/index.html'
if not goldtool.exists():
 s=(ROOT/'tools/index.html').read_text().replace('https://blackgoldmarket.us/tools/','https://blackgoldmarket.us/tools/gold-position-size/')
 write('tools/gold-position-size/index.html',s)
routes['/tools/gold-position-size/']='Gold position size calculator'
def num(name,label,value,minimum='0',maximum='',step='any'):
 return f'<label>{label}<input name="{name}" type="number" value="{value}" min="{minimum}" '+(f'max="{maximum}" ' if maximum else '')+f'step="{step}" required></label>'
def calculator(path,title,desc,fields,method,explanation):
 body='<div class="calculator-layout"><form class="calculator utility-form" data-method="'+method+'"><div class="form-grid">'+fields+'</div><button class="button" type="submit">Calculate</button><p class="utility-error" role="alert"></p></form><section class="results" aria-live="polite"><p class="eyebrow">RESULT / YOUR INPUTS</p><div class="utility-result">Enter values and calculate.</div></section></div><section class="notice"><h2>Method and limitations</h2><p>'+explanation+'</p></section><p><a href="/tools/">← All tools</a></p>'
 page('/tools/'+path+'/',title,desc,body)
calculator('position-size','Forex position size','Calculate quantity from stop distance and pip value in your account currency.',num('balance','Account balance',5000,'0.01')+num('risk','Risk (%)',1,'0.0001','100')+num('stop','Stop distance (pips)',25,'0.00001')+num('pipValue','Pip value per lot (account currency)',10,'0.000001')+num('step','Lot increment',0.01,'0.000001'),'position','Risk budget = balance × risk %. Lots = budget ÷ (stop pips × pip value per lot), rounded down to the lot increment. Use the pip-value tool or your broker’s contract specification. Costs, gaps, slippage and margin checks are excluded.')
calculator('pip-value','Pip value calculator','Translate one pip into the account currency using an explicit conversion rate.',num('units','Position size (base units)',10000,'0.00001')+num('pip','Pip size',0.0001,'0.00000001')+num('rate','Account-currency units per 1 quote-currency unit',1,'0.00000001'),'pip','Pip value = base units × pip size × quote-to-account conversion rate. Example: for EUR/USD held in USD, the conversion rate is 1. For EUR/JPY held in USD, enter USD per JPY, not JPY per USD. Use a current rate and the exact contract specification.')
calculator('gain-loss','Gain, loss and recovery','Measure the change in a balance and the gain needed to recover a drawdown.',num('start','Starting balance',10000,'0.01')+num('end','Ending balance',8000,'0'),'gain','Change % = (ending − starting) ÷ starting × 100. When ending is lower, recovery % = (starting − ending) ÷ ending × 100. A zero ending balance has no finite percentage recovery. Deposits and withdrawals must be excluded for this to describe trading performance.')
calculator('pivot-points','Classical pivot points','Calculate a central pivot and three support and resistance references.',num('high','Previous-period high',2510,'0.000001')+num('low','Previous-period low',2490,'0.000001')+num('close','Previous-period close',2500,'0.000001'),'pivot','P = (H + L + C) ÷ 3. R1 = 2P − L; S1 = 2P − H. R2 = P + (H − L); S2 = P − (H − L). R3 = H + 2(P − L); S3 = L − 2(H − P). Use one consistent session and timeframe. Levels describe a formula, not guaranteed turning points.')
calculator('expectancy','Trade expectancy','Compare win rate, average outcomes and costs in the same monetary or risk units.',num('winRate','Win rate (%)',40,'0','100')+num('win','Average winning trade (before costs)',2,'0')+num('loss','Average losing trade (positive magnitude)',1,'0.000001')+num('cost','Average cost per trade',0.1,'0'),'expectancy','Expectancy = win probability × average win − loss probability × average loss − average cost. Break-even win rate = (average loss + cost) ÷ (average win + average loss). Use the same units in all inputs. A small or biased sample can mislead; this is not a forecast.')
calculator('risk-reward','Risk and reward ratio','Compare entry, stop and target distances for either a long or a short trade.',num('entry','Entry price',2500,'0.00001')+num('stop','Stop-loss price',2490,'0.00001')+num('target','Target price',2520,'0.00001'),'reward','Reward-to-risk = absolute target distance ÷ absolute stop distance. The target must be on the opposite side of entry from the stop. Break-even win rate before costs assumes every win reaches the target and every loss equals the planned stop; partial exits and slippage change it.')
series='<label>Series A closing prices, oldest first<textarea name="a" rows="6" required>100, 102, 101, 104, 103, 106</textarea></label><label>Series B closing prices on the same dates<textarea name="b" rows="6" required>200, 204, 202, 208, 206, 212</textarea></label>'
calculator('correlation','Return correlation','Paste two aligned closing-price series. The example inputs are synthetic, not market data.',series,'correlation','The tool converts adjacent prices to simple percentage returns, then calculates Pearson correlation. Use at least four positive prices per series, matching dates and frequency. Constant returns have undefined correlation. Different windows can produce different results; correlation is not causation.')
calculator('volatility','Historical volatility','Measure dispersion in a closing-price series. The example is synthetic.', '<label>Closing prices, oldest first<textarea name="prices" rows="6" required>100, 102, 101, 104, 103, 106</textarea></label>'+num('periods','Observations per year',252,'1','100000','1'),'volatility','Calculate adjacent log returns, their sample standard deviation, and multiply by the square root of observations per year. The square-root annualization is an assumption, not a forecast. Use 252 for a conventional business-day sample or 365 for daily crypto only when it matches your data. At least four positive prices are required.')
calculator('risk-sentiment','Risk sentiment worksheet','Summarize four observations from the same interval. Manual inputs only; no live market signal.',num('equity','Broad equity index change (%)',0,'-100')+num('aud','AUD/JPY change (%)',0,'-100')+num('vix','VIX change (%)',0,'-100')+num('credit','Credit spread change (basis points)',0,'-100000'),'sentiment','This educational checklist assigns +1 for rising equities, rising AUD/JPY, falling VIX or narrowing credit spreads; −1 for the reverse; 0 for unchanged values. It sums four signs equally. It ignores magnitude and is not a calibrated forecasting model. Assets can respond differently to the same shock.')
currencies=['USD','EUR','GBP','JPY','CHF','AUD','CAD','NZD','VND','SGD','HKD','CNY','INR','KRW']
opts=lambda selected:''.join(f'<option {"selected" if c==selected else ""}>{c}</option>' for c in currencies)
page('/tools/currency-converter/','Currency converter','Convert using daily reference rates from Frankfurter. These are not executable broker, bank or cash-exchange quotes.','<form id="currency-form" class="calculator"><div class="form-grid">'+num('amount','Amount',100,'0')+'<label>From<select name="base">'+opts('USD')+'</select></label><label>To<select name="quote">'+opts('EUR')+'</select></label></div><button class="button" type="submit">Get reference conversion</button></form><div id="currency-result" class="notice" role="status">Choose currencies and request a conversion.</div><p class="meta">The response shows the publication date. Weekends and holidays can use the latest available business-day rate. Availability depends on the external provider. <a href="https://frankfurter.dev/">Source and methodology: Frankfurter</a>.</p>')
page('/tools/market-hours/','Forex session clock','Compare representative financial-centre hours in your time zone, with daylight saving handled for the selected date.','<div class="library-controls"><label>Reference date<input type="date" id="session-date"></label><label>Display time zone<select id="session-zone"><option value="UTC">UTC</option><option value="Asia/Ho_Chi_Minh">Ho Chi Minh City</option><option value="Europe/London">London</option><option value="America/New_York">New York</option><option value="Asia/Tokyo">Tokyo</option><option value="Australia/Sydney">Sydney</option></select></label></div><div id="session-table" class="table-scroll" aria-live="polite"></div><div class="notice"><h2>Representative sessions, not an exchange schedule</h2><p>London 08:00–17:00, New York 08:00–17:00, Tokyo 09:00–18:00 and Sydney 08:00–17:00 use each centre’s local time. The selected date is the opening date in that centre. Weekends are shown closed; local holidays and broker maintenance breaks are not modelled. Spot FX is decentralized. Check your broker for actual XAU/USD and product hours.</p></div>')
page('/tools/trade-journal/','Practice trade journal','Record and review practice trades on this browser. Data is not sent to Black Gold Market or synced between devices.','<form id="journal-form" class="calculator"><div class="form-grid"><label>Date<input name="date" type="date" required></label><label>Symbol<input name="symbol" maxlength="24" value="XAU/USD" required></label>'+num('risk','Planned risk (account currency)',50,'0.01')+num('pnl','Net result after costs (same currency)',0,'-1000000000')+'<label class="full">Process notes<textarea name="notes" rows="3" maxlength="2000" placeholder="Setup, execution and one lesson" required></textarea></label></div><button class="button" type="submit">Save practice trade</button><p id="journal-status" role="status"></p></form><div id="journal-summary" class="notice" aria-live="polite"></div><div class="table-scroll" id="journal-rows"></div><p><button class="button secondary" id="journal-export">Download journal backup</button></p><label>Restore a backup<input type="file" id="journal-import" accept=".json,application/json"></label><p class="meta">Export a backup before changing browsers or clearing website storage. Imported records replace the local journal only after confirmation.</p>')
page('/tools/regulators/','Regulator directory','Start with official resources. Verify the exact legal entity, permissions and contact details; registration does not promise profits or eliminate risk.',cards([('https://www.fca.org.uk/consumers/fca-firm-checker','UNITED KINGDOM','FCA Firm Checker','Check a firm and match its official contact details.'),('https://www.cftc.gov/check','UNITED STATES','CFTC registration checks','Find official routes to check derivatives intermediaries.'),('https://www.nfa.futures.org/basicnet/','UNITED STATES','NFA BASIC','Research registration and disciplinary information.'),('https://asic.gov.au/online-services/search-asic-registers/','AUSTRALIA','ASIC registers','Locate official company and financial-service registers.')])+'<div class="notice"><h2>Check the entity, not just the brand</h2><p>A group can use multiple legal entities with different permissions. Match the register’s website, phone and address independently. Do not rely on a registration number sent by a salesperson. Product protections vary by jurisdiction.</p><a href="/journal/how-to-check-forex-broker-license.html">Read the broker-checking guide →</a></div>')
tools=[('gold-position-size','Gold position size','Size XAU/USD using ounces per lot and a stop distance.'),('position-size','Forex position size','Use stop pips and pip value in your account currency.'),('pip-value','Pip value','Translate a pip into account-currency value.'),('risk-reward','Risk and reward','Compare entry, stop and target distances.'),('gain-loss','Gain, loss and recovery','Calculate balance change and the recovery hurdle.'),('pivot-points','Classical pivots','Calculate three support and resistance references.'),('expectancy','Expectancy','Include win rate, payoff size and costs.'),('currency-converter','Currency converter','Fetch dated daily reference rates.'),('market-hours','Session clock','Compare financial-centre hours with daylight saving.'),('correlation','Correlation','Measure co-movement from aligned price samples.'),('volatility','Volatility','Calculate sample and annualized return dispersion.'),('risk-sentiment','Sentiment worksheet','Compare four manually entered risk observations.'),('trade-journal','Practice journal','Save trade records locally and export a backup.'),('regulators','Regulator directory','Find official firm-checking resources.')]
page('/tools/','Trading tools','Calculate, compare and practice. Inputs and assumptions are shown with every tool.',cards([('/tools/'+s+'/','TOOL',t,d) for s,t,d in tools]))
# Official embeddable market displays; third-party attribution stays visible.
def widget(kind,config,fallback,height=600):
 data=esc(json.dumps(config,separators=(',',':')))
 return f'<section class="market-widget" data-widget="{kind}" data-config="{data}" style="--widget-height:{height}px"><div class="widget-mount"></div><p class="widget-loading" role="status">Loading market display…</p><noscript>JavaScript is required for the embedded display.</noscript><p class="widget-source"><a href="{fallback}" target="_blank" rel="noopener">Open this market on TradingView</a> · Data and display by TradingView</p></section>'
chart={'autosize':True,'symbol':'OANDA:XAUUSD','interval':'D','timezone':'Etc/UTC','theme':'light','style':'1','locale':'en','allow_symbol_change':True,'hide_side_toolbar':False,'calendar':False}
page('/markets/','Market overview','Explore gold and the markets around it. Displays are supplied by TradingView; availability and delay depend on the symbol and data source.',cards([('/markets/forex/','FOREX','Currency markets','Cross rates, relative changes and a sortable screener.'),('/markets/crypto/','CRYPTO','Digital-asset markets','A market-cap heatmap and chart with symbol selection.'),('/markets/strength/','DAILY REFERENCE DATA','Currency strength','Compare a fixed basket over a selected window.')])+widget('advanced-chart',chart,'https://www.tradingview.com/symbols/XAUUSD/')+'<p class="meta">This is a market observation workspace, not an order-entry system or a source of guaranteed signals.</p>')
page('/markets/forex/','Forex market workspace','Compare the major currencies, then inspect symbols in the screener. Green and red describe changes over the displayed interval, not trade recommendations.',widget('forex-heat-map',{'width':'100%','height':450,'currencies':['EUR','USD','JPY','GBP','CHF','AUD','CAD','NZD'],'isTransparent':False,'colorTheme':'light','locale':'en'},'https://www.tradingview.com/markets/currencies/',450)+widget('screener',{'width':'100%','height':600,'defaultColumn':'overview','defaultScreen':'general','market':'forex','showToolbar':True,'colorTheme':'light','locale':'en'},'https://www.tradingview.com/forex-screener/')+'<p><a href="/markets/strength/">Compare daily basket strength →</a> · <a href="/tools/volatility/">Calculate volatility from your data →</a></p>')
page('/markets/crypto/','Crypto market workspace','Compare assets with a heatmap, then inspect a chart. Market capitalization is not a measure of available exit liquidity.',widget('crypto-coins-heatmap',{'dataSource':'Crypto','blockSize':'market_cap_calc','blockColor':'change','locale':'en','colorTheme':'light','hasTopBar':True,'isDataSetEnabled':True,'isZoomEnabled':True,'hasSymbolTooltip':True,'width':'100%','height':600},'https://www.tradingview.com/markets/cryptocurrencies/')+widget('advanced-chart',{**chart,'symbol':'BITSTAMP:BTCUSD'},'https://www.tradingview.com/symbols/BTCUSD/')+'<p><a href="/learn/crypto/">Learn how crypto markets work →</a></p>')
page('/markets/strength/','Currency strength comparison','Compare eight currencies using daily reference rates from Frankfurter. This is not an intraday strength signal.','<form id="strength-form" class="calculator"><label>Lookback window<select name="days"><option value="7">7 calendar days</option><option value="30" selected>30 calendar days</option><option value="90">90 calendar days</option></select></label><p><button class="button" type="submit">Compare currencies</button></p></form><div id="strength-result" class="notice" role="status">Choose a window and load the comparison.</div><div class="notice"><h2>How the basket is measured</h2><p>The basket is USD, EUR, GBP, JPY, CHF, AUD, CAD and NZD. For each currency, the tool calculates its appreciation relative to USD between two dated observations, subtracts the basket’s mean log change, and converts the result to a percentage. USD participates in the basket; weights are equal. Only dates shared by all eight currencies are used. Weekends and publication gaps can shorten the actual window. Rates are reference values, not executable quotes.</p><a href="https://frankfurter.dev/">Data source: Frankfurter</a></div>')
page('/news/','Market news','Follow headlines in the external news feed and read Black Gold Market’s background guides. News can be revised; verify important releases with the original publisher.',widget('timeline',{'feedMode':'all_symbols','isTransparent':False,'displayMode':'regular','width':'100%','height':650,'colorTheme':'light','locale':'en'},'https://www.tradingview.com/news/',650)+cards([('/economic-calendar/','EVENTS','Plan around releases','View the economic calendar and event-reading checklist.'),('/journal/how-to-trade-around-high-impact-news.html','BACKGROUND','Prepare for high-impact news','Understand execution risks around scheduled events.'),('/journal/how-central-banks-affect-the-price-of-gold.html','BACKGROUND','Central banks and gold','Read the mechanics behind policy headlines.')]))
page('/economic-calendar/','Economic calendar','Check event times, currencies and reported figures in the TradingView calendar. Confirm the displayed time zone before planning a session.',widget('events',{'colorTheme':'light','isTransparent':False,'width':'100%','height':650,'locale':'en','importanceFilter':'-1,0,1','countryFilter':'us,gb,eu,de,fr,jp,au,ca,nz,ch,cn'},'https://www.tradingview.com/economic-calendar/',650)+'<div class="three"><section><h2>Before the release</h2><p>Record the release time, measurement period and expected figure. Decide whether your plan permits exposure during the event.</p></section><section><h2>Read the details</h2><p>Compare actual, forecast and prior figures. Check revisions and definitions. A surprise does not dictate one price response.</p></section><section><h2>Check execution</h2><p>Spreads and slippage may change sharply. The calendar’s importance label does not establish a safe trading window.</p></section></div><p>Official release sources: <a href="https://www.bls.gov/schedule/news_release/">US Bureau of Labor Statistics</a> · <a href="https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm">Federal Reserve</a> · <a href="https://www.bea.gov/news/schedule">Bureau of Economic Analysis</a>.</p>')
# Category hubs use existing articles; runtime refresh includes future additions from journal/index.html.
category_rules={
 'technical-analysis':('Technical analysis',r'trend|structure|support|confluence|round-numbers|r1-r2|order|gold-vs|correlation|session'),
 'psychology':('Trading psychology',r'emotion|revenge|patience|psychology|discipline|overtrading|consistent|marathon|mentor|profit-too-early|recover-from'),
 'systems':('Trading systems',r'strategy|edge|test-your|win-rate|expectancy|consistent|track|probability|managing-the-trade|successful-trader|better-at')}
journal=(ROOT/'journal/index.html').read_text()
existing=re.findall(r'<a class="jcard".*?</a>',journal,re.S)
for key,(title,pattern) in category_rules.items():
 chosen=[re.sub(r'href="(?!/|https)([^"]+)"',r'href="/journal/\1"',c) for c in existing if re.search(pattern,c.split('>')[0],re.I)]
 body='<p><a href="/journal/">Search the full journal →</a></p><div class="category-feed j-grid" data-category="'+key+'">'+''.join(chosen)+'</div>'
 page('/trading/'+key+'/',title,'Selected educational articles from the Black Gold Market journal. These are background guides, not current trade calls.',body)
page('/trading/','Trading library','Build your market-reading skills, trading process and discipline with the existing journal and the expanded academy.',cards([('/trading/'+k+'/','JOURNAL',t,'Explore related educational articles.') for k,(t,_) in category_rules.items()]+[('/trading/trade-ideas/','PLANNING','Trade ideas','Use a scenario template and follow the existing community channel.'),('/learn/crypto/','CRYPTO','Crypto guides','Read original lessons on digital-asset markets and safety.'),('/journal/','ARCHIVE','All journal articles','Search and filter the complete published library.')]))
page('/trading/trade-ideas/','Trade idea planner','Write a scenario before looking for an entry. This page contains a planning worksheet, not live buy or sell calls.','<form id="plan-form" class="calculator"><div class="form-grid"><label>Market and timeframe<input name="market" value="XAU/USD · 1 hour" maxlength="100" required></label><label>Context<input name="context" placeholder="Trend, range, scheduled event…" maxlength="300" required></label><label>Entry condition<textarea name="entry" rows="3" required maxlength="2000"></textarea></label><label>Invalidation condition<textarea name="invalidation" rows="3" required maxlength="2000"></textarea></label><label>Risk and exit plan<textarea name="risk" rows="3" required maxlength="2000"></textarea></label><label>When to stand aside<textarea name="skip" rows="3" required maxlength="2000"></textarea></label></div><button class="button" type="submit">Download my plan</button></form><div class="notice"><h2>Follow the existing channel</h2><p>Raphael shares gold analysis and trade ideas on Telegram. Read the reasoning and risks; a posted setup is not a guarantee.</p><a href="https://t.me/+h-5A-mdBmhA5ZWQ1">Open the Black Gold Market channel →</a></div>')
page('/community/','Black Gold Market community','Follow the existing Telegram channel for gold market discussion and the reasoning behind posted setups.',cards([('https://t.me/+h-5A-mdBmhA5ZWQ1','TELEGRAM','Open the community channel','Use the existing channel. Posting permissions are controlled by its administrators.'),('/learn/','NEW HERE','Start with the learning path','Read the foundations before risking money.'),('/tools/trade-journal/','PRACTICE','Keep your own journal','Save a private, browser-local record of your practice trades.')])+'<div class="notice"><h2>Participate thoughtfully</h2><p>Discuss the reasoning, timeframe and invalidation behind an idea. Do not share account credentials, recovery phrases or private financial details. There is no separate on-site forum. Analysis membership availability is shown on the account page.</p></div>')
page('/faq/','Frequently asked questions','How the learning resources, market displays and community work.',''.join(f'<details class="faq-item"><summary>{q}</summary><p>{a}</p></details>' for q,a in [
 ('Are the courses and tools free?','The public academy, glossary, quizzes and calculators are free. The existing Trader’s Kit is optional and described separately on its own page.'),
 ('Will progress follow me to another device?','No. Lesson progress, quiz scores and practice-journal records are stored in this browser. Use the backup controls to export and restore supported records.'),
 ('Are market prices live?','TradingView supplies the embedded displays. Data timing varies by instrument and provider. The currency converter and strength comparison use dated daily reference rates, not executable quotes.'),
 ('Do you provide guaranteed trading results?','No. Educational resources, calculator outputs and community trade ideas cannot guarantee a profit or limit every possible loss.'),
 ('Why is a market widget blank?','A content blocker, network issue or the provider can prevent a display from loading. Use the adjacent link to open the source, or try again later. We do not substitute invented prices.'),
 ('Can I create a member account here?','Visit My account to check member-registration availability. Public learning resources and browser-local progress do not require an account.'),
 ('Where can I discuss a trade?','Use the existing Telegram channel and any discussion features its administrators enable. There is no separate web forum yet.'),
 ('How do I get the Blueprint or the Kit?','Use the Free Blueprint and The Kit links. Their existing signup and purchase pages remain available.')]))
page('/contact/','Contact Black Gold Market','Use the existing community channel to find its current contact options.','<div class="notice"><h2>Community and general enquiries</h2><p>Visit the official Telegram channel and use the contact information provided there. Do not send passwords, payment-card details, private keys or recovery phrases.</p><a class="button" href="https://t.me/+h-5A-mdBmhA5ZWQ1">Open official channel</a></div>')
page('/partners/','Partnership enquiries','For enquiries about educational collaborations or advertising, use the contact route below.','<div class="notice"><h2>Contact the team</h2><p>This page does not list approved brokers, paid endorsements or an affiliate programme. Any proposal needs to be reviewed by the Black Gold Market team.</p><a href="/contact/">Contact Black Gold Market →</a></div>')
page('/privacy/','Privacy and website data','A practical explanation of the data features used on this website.','<article class="lesson-body"><h2>Browser-local learning records</h2><p>Lesson completion, quiz scores and practice-journal records are stored in your browser. The website does not upload these records to a Black Gold Market account. Exported backup files are created on your device. Clearing website storage can erase local records.</p><h2>Analysis membership</h2><p>When member registration opens, account email, authentication data, membership expiry and payment-request records (including transaction IDs and review notes) are stored with Supabase. Transaction records are visible to their owner and authorized administrators. USDT transfers are public blockchain records. Session credentials are stored in this browser to keep you signed in; sign out on shared devices. For account-data requests, contact the team.</p><h2>Existing analytics and signup forms</h2><p>The site includes Google Analytics to measure visits and interactions. The Blueprint and Telegram signup forms send submitted information to the existing subscription service. Do not include sensitive financial or identity information in learning notes or contact enquiries.</p><h2>External data and links</h2><p>Market widgets connect to TradingView. Currency tools request reference data from Frankfurter. Those requests and any external links are subject to the providers’ own policies. Market displays may set or access information according to their services.</p><h2>Your controls</h2><p>You can manage website storage and cookies in your browser, choose whether to submit signup forms, and use the unsubscribe link in received emails. For questions about submitted information, use the <a href="/contact/">existing contact route</a>.</p></article>')
page('/risk-disclosure/','Risk disclosure','Understand the limits of educational content, market displays and calculator outputs.','<article class="lesson-body"><h2>Losses are possible</h2><p>Gold, foreign exchange, crypto assets and leveraged products can produce substantial losses. Leverage magnifies exposure; stop orders can execute beyond their trigger during gaps or poor liquidity. Product protections depend on the provider, contract and jurisdiction.</p><h2>Education and examples</h2><p>Lessons, quizzes, planning worksheets and community ideas are not personal financial advice. Hypothetical examples are not performance claims. A completed course or high quiz score does not demonstrate suitability for trading.</p><h2>Tools and third-party data</h2><p>Calculations depend on your inputs and their stated assumptions. They may exclude costs, margin requirements and execution risks. Market displays and daily reference rates can be delayed, unavailable or revised. Verify contract terms and executable prices independently before making decisions.</p><h2>Further reading</h2><p><a href="https://www.cftc.gov/LearnAndProtect/AdvisoriesAndArticles/ForeignCurrencyTrading/index.htm">CFTC: foreign currency trading</a> · <a href="https://www.investor.gov/crypto-assets">Investor.gov: crypto assets</a>.</p></article>')
from premium_pages import build_premium
quote=(ROOT/'scripts/templates/quote.html').read_text()
build_premium(page,esc,quote)
from member_pages import build_members
build_members(page)
# Shared navigation on portal entry points; do not touch article publishing templates.
for name in ['index.html','journal/index.html','learn/index.html','tools/gold-position-size/index.html']:
 s=(ROOT/name).read_text()
 s=re.sub(r'<a class="skip".*?</a>','',s,count=1,flags=re.S)
 s=re.sub(r'<header class="site-header">.*?</header>',nav,s,count=1,flags=re.S)
 if '/assets/premium.css' not in s:s=s.replace('</head>','<link rel="stylesheet" href="/assets/premium.css"></head>')
 if '/assets/academy.css' not in s:s=s.replace('</head>','<link rel="stylesheet" href="/assets/academy.css"></head>')
 if '/assets/academy.js' not in s:s=s.replace('</body>','<script defer src="/assets/tool-math.js"></script><script defer src="/assets/academy.js"></script></body>')
 if 'class="site-footer"' in s:s=re.sub(r'<footer class="site-footer">.*?</footer>',footer,s,count=1,flags=re.S)
 else:s=re.sub(r'<footer.*?</footer>',footer,s,count=1,flags=re.S)
 if name=='index.html':
  if 'class="daily-quote"' not in s:s=s.replace('</main>',quote+'</main>')
  if '<!-- analysis-discovery -->' not in s:s=s.replace('<!-- resource-expansion -->','<!-- analysis-discovery --><section class="shell analysis-discovery"><div><p class="eyebrow">ANALYSIS &amp; PREPARATION</p><h2>Start with the context.<br>Then build the plan.</h2><p>Read event guides, scenario-planning notes and weekly review methods.</p><a class="button secondary" href="/analysis/">Explore Analysis →</a></div><div><span class="premium-label">THE TRADER’S KIT</span><h2>Go deeper with the book and community.</h2><p>Compare the existing packages, from $9 one-time.</p><a class="button premium-button" href="/vip/#tickets">See Kit packages →</a></div></section><!-- resource-expansion -->')
  banner=(ROOT/'scripts/templates/homepage-carousel.html').read_text()
  if '<section class="hero-carousel"' in s:
   s=re.sub(r'<section class="hero-carousel".*?</section>',lambda m:banner,s,count=1,flags=re.S)
  else:
   s=re.sub(r'<div class="shell intro">.*?</section>',lambda m:banner,s,count=1,flags=re.S)
  if '/assets/carousel.css' not in s:s=s.replace('</head>','<link rel="stylesheet" href="/assets/carousel.css"></head>')
  if '/assets/carousel.js' not in s:s=s.replace('</body>','<script defer src="/assets/carousel.js?v=2"></script></body>')
 if name=='index.html' and '<!-- resource-expansion -->' not in s:
  s=s.replace('<section class="learning-band">','<!-- resource-expansion --><section class="shell resource-home"><p class="eyebrow">YOUR TRADING WORKSPACE</p><h2>More ways to learn and prepare.</h2>'+cards([('/markets/','MARKETS','See the bigger picture','Gold charts, FX and crypto market displays.'),('/economic-calendar/','CALENDAR','Know what is scheduled','Explore upcoming economic releases.'),('/learn/forex/','ACADEMY','Build the foundations','33 Forex lessons, plus a 12-lesson Crypto course.'),('/glossary/','GLOSSARY','Make sense of the language','Search definitions across gold, FX and crypto.'),('/quizzes/','QUIZZES','Check your understanding','Four quizzes with explanations.'),('/tools/','TOOLS','Put numbers to the plan','Position sizing, pivots, recovery, journal and more.')])+'</section><section class="learning-band">')
  s=s.replace('href="/tools/">Open trading tools','href="/tools/">Open trading tools')
 write(name,s)
page('/site-map/','Explore Black Gold Market','Find the academy, market displays, calculators and supporting resources in one place.','<ul class="directory">'+''.join(f'<li><a href="{u}">{esc(t)}</a></li>' for u,t in sorted(routes.items()))+'<li><a href="/journal/">All journal articles</a></li><li><a href="/learn/">Gold learning path</a></li><li><a href="/about.html">About Raphael</a></li><li><a href="/vip/">The Trader’s Kit</a></li></ul>')
# Add new URLs without deleting the publisher's existing sitemap entries.
sitemap=(ROOT/'sitemap.xml').read_text()
for u in routes:
 url='https://blackgoldmarket.us'+u
 if '<loc>'+url+'</loc>' not in sitemap:sitemap=sitemap.replace('</urlset>','<url><loc>'+url+'</loc></url>\n</urlset>')
write('sitemap.xml',sitemap)
write('content/portal-routes.json',json.dumps(routes,indent=2))
print(f'Built {len(routes)} routes, {len(lessons)} original lessons, {len(terms)} glossary terms and {sum(len(q["questions"]) for q in quizzes.values())} quiz questions.')
# Apply after generation, including legacy pages and newly published journal files.
from branding import apply_branding
print('Branding updated:',apply_branding())
