"""Public analysis and existing-kit discovery; no simulated authentication or paywall."""
def build_premium(page, esc, quote):
    def offer():
        return '''<section class="premium-offer"><div class="offer-heading"><span class="premium-label">THE TRADER’S KIT</span><h2>Bring more structure to your preparation.</h2><p>Continue with The Long Game, a protect-first checklist and the private community included in the existing Kit.</p></div><div class="offer-content"><img src="/book/the-long-game/pages/001.jpg" width="893" height="1263" alt="The Long Game book cover" loading="lazy"><div><h3>Choose the support that fits your routine.</h3><ul><li>The Long Game book and the Blueprint in every package.</li><li>Private Long Game Room access in every package.</li><li>VIP adds monthly group Q&amp;A and The Week Ahead.</li><li>Very VIP adds priority questions and early access to new material.</li></ul><a class="button premium-button" href="/vip/#tickets">See packages and what’s included →</a><p class="meta">From $9 one-time. Materials and room access follow the payment-confirmation steps. Buying a Kit does not unlock articles on this website automatically.</p></div></div></section>'''
    articles=[
      ('preparing-gold-for-inflation-data','Event preparation','Preparing gold scenarios around inflation data','/assets/hero/how-inflation-affects-the-price-of-gold.png','Inflation headlines matter through expectations, rates and the dollar. Use a scenario map to separate those channels before considering an entry.',[
        ('Start with the question, not the direction','What would this release change about the market’s expected path for policy? Separate the headline and core measures, the monthly and annual comparisons, and any revisions. A bigger number is not a complete trading instruction: its surprise relative to expectations and the broader backdrop both matter.'),
        ('Build three conditional scenarios','For a stronger-than-expected release, observe whether yields and the dollar actually confirm a restrictive-policy interpretation. For a weaker release, check whether the response persists beyond the first price spike. For an in-line release, consider whether positioning, revisions or the next scheduled event dominate instead. These are observation prompts; gold can react differently in each setting.'),
        ('Define the conditions for doing nothing','Record the release time and your chart timeframe. Decide which spread, liquidity or price behaviour would keep you out. A stop is an order instruction rather than a guarantee of the fill price. If the release changes the execution environment beyond what your process was tested for, observation may be the more consistent choice.'),
        ('Review what changed','After the event, compare your written scenarios with the actual sequence: the data, initial response, follow-through and eventual close. Record whether the reasoning was useful even if no trade qualified. Review the release from its official source rather than relying only on a headline.')],'/economic-calendar/','Open the economic calendar'),
      ('building-a-gold-watchlist','Scenario planning','A gold watchlist begins with invalidation','/assets/hero/how-to-read-golds-trend-and-market-structure.png','Turn a directional view into a plan you can review: context, trigger, invalidation and the conditions for standing aside.',[
        ('Give the higher timeframe one job','Describe the environment as a trend, range or transition under a rule you can explain. Mark the areas that would change that description. This is context, not permission to take every lower-timeframe move in the same direction.'),
        ('Separate an idea from an order','An idea describes a possibility. An order requires a defined trigger, quantity and exit logic. For a hypothetical long setup, write what must happen before entry and what would make the long thesis invalid. For a short setup, write the corresponding conditions independently rather than simply reversing a bullish narrative.'),
        ('Size after defining invalidation','With a hypothetical $50 budget, a $10 stop distance and 100 ounces per lot, the planned size before costs is 0.05 lots. If the stop distance doubles, the same budget supports half the quantity. Contract increments, fees and slippage must also be considered; do not move an invalidation level merely to permit larger size.'),
        ('Write an expiry for the idea','A setup can become irrelevant after a release, a session change or a structural break. Give the plan a review time and a condition that cancels it. A missed move is not a reason to keep an expired thesis alive.')],'/trading/trade-ideas/','Build your own scenario plan'),
      ('reviewing-the-trading-week','Weekly review method','Review the week without rewriting the story','/assets/hero/how-to-be-a-consistent-trader.png','A useful recap records what was known at the time, what happened and what the process needs to change.',[
        ('Reconstruct the sequence','List the week’s major releases and policy events, then connect them to observed price responses. Keep the initial reaction separate from the later move. A neat explanation written after the close may hide the uncertainty faced during the session.'),
        ('Review results in comparable units','Record net results after costs as well as the initial risk of each trade. A result divided by its initial planned risk gives an R multiple. This helps compare different position sizes, but it does not replace an account-level record of cash flows and drawdown.'),
        ('Separate process errors from normal losses','A valid setup can lose, and a rule-breaking trade can win. Review whether the entry conditions, size and exit followed the plan. Look for repeated behaviours such as entering before confirmation or increasing size after a loss. Do not infer an edge from a handful of outcomes.'),
        ('Choose one change you can evaluate','Write one concrete action for the next review period: for example, calculate size before every demo order or exclude one untested news window. Define how compliance will be measured. Keep the rest of the process stable enough to assess whether that change helped.')],'/tools/trade-journal/','Open the practice journal')
    ]
    # These are evergreen public guides, not invented dated market calls or paid articles.
    from pathlib import Path
    root=Path(__file__).resolve().parents[1]
    rows=''
    for slug,kind,title,img,intro,sections,url,label in articles:
        if not (root/img.lstrip('/')).exists():img='/assets/inside/inside-1-chart.jpg'
        rows+=f'<article class="analysis-row"><a href="/analysis/{slug}/"><img src="{img}" alt="" loading="lazy" width="640" height="420"></a><div><p class="analysis-meta">{esc(kind)} <span class="free-label">FREE GUIDE</span></p><h2><a href="/analysis/{slug}/">{esc(title)}</a></h2><p>{esc(intro)}</p><a class="read" href="/analysis/{slug}/">Read the guide →</a></div></article>'
        body=f'<p class="analysis-meta">Black Gold Market · {esc(kind)} · Evergreen educational guide</p><div class="analysis-layout"><article class="analysis-body"><aside class="analysis-notice"><strong>Prepare with a repeatable process.</strong><p>Explore the book, checklist and community in the Trader’s Kit. <a href="/vip/#tickets">See what each package includes →</a></p></aside><img class="analysis-hero" src="{img}" alt="Educational gold trading illustration" width="640" height="420">'
        body+=''.join(f'<section><h2>{esc(h)}</h2><p>{esc(p)}</p></section>' for h,p in sections)
        body+=f'<p><a class="button secondary" href="{url}">{label} →</a></p><p class="meta">This is a free educational guide, not a current market call. Examples are hypothetical and do not promise an outcome.</p>'+offer()+'''</article><aside class="analysis-sidebar"><span class="premium-label">GO FURTHER</span><h2>The Sustainable Trader’s Kit</h2><p>The book, the Blueprint and a private community for putting a process into practice.</p><a href="/vip/#tickets">Compare the packages →</a><hr><h3>Prepare your session</h3><a href="/economic-calendar/">Economic calendar</a><a href="/tools/gold-position-size/">Gold position size</a><a href="/analysis/">All analysis guides</a></aside></div>'''
        page('/analysis/'+slug+'/',title,intro,body)
    page('/analysis/','Analysis & market preparation','Read original guides to event preparation, scenario planning and reviewing your trading process.', '<div class="analysis-layout"><div>'+rows+offer()+'''</div><aside class="analysis-sidebar"><span class="premium-label">VIP PACKAGE</span><h2>The Week Ahead</h2><p>The existing VIP package includes a weekly note on key zones and monthly group Q&amp;A with Raphael.</p><a class="button premium-button" href="/vip/#tickets">Explore VIP benefits</a><p class="meta">Delivered through the existing Kit/community service. These public guides do not require a purchase.</p></aside></div>'''+quote)
    body='''<section class="premium-intro"><div><span class="premium-label">ANALYSIS PREMIUM</span><h2>Go deeper into market preparation.</h2><p>A dedicated membership for premium analysis and event guides.</p><a class="button premium-button" href="#premium-details">Explore membership plans →</a></div></section><section id="premium-details"><p class="eyebrow">MEMBERSHIP PLANS · COMING SOON</p><h2>Choose monthly or annual access</h2><div class="premium-plans analysis-plans"><article class="premium-plan"><span class="premium-label">1 Month</span><h3>One month of Analysis Premium</h3><p class="package-price">$29<span>per month</span></p><p>Total: $29 for one month of access.</p><p class="meta">Enrollment is not open yet.</p></article><article class="premium-plan featured"><span class="premium-label">Annual · Save 41%</span><h3>A full year of Analysis Premium</h3><p class="package-price">$17<span>per month equivalent</span></p><p>Total: $204 paid upfront for one year of access.</p><p class="meta">Enrollment is not open yet.</p></article></div></section><section class="premium-delivery"><h2>Membership is being prepared</h2><p>Member accounts and protected article access are not live yet. Payments for Analysis Premium are not currently accepted.</p><p>Planned payment methods: PayPal and USDT. Renewal and payment instructions will be available when enrollment opens.</p><a class="button secondary" href="/analysis/">Read the free analysis guides →</a></section><section><h2>Looking for the Trader’s Kit?</h2><p>The book and community packages are a separate purchase and do not include this Analysis membership.</p><a href="/vip/">View the existing Trader’s Kit →</a></section>'''+quote
    page('/premium/','Analysis Premium','Monthly and annual membership plans for Black Gold Market analysis. Enrollment coming soon.',body)
