"""Public analysis and existing-kit discovery; no simulated authentication or paywall."""
def build_premium(page, esc, quote):
    def offer():
        return '''<section class="premium-offer"><div class="offer-heading"><span class="premium-label">THE TRADER’S KIT</span><h2>Bring more structure to your preparation.</h2><p>Continue with The Long Game, a protect-first checklist and the private community included in the existing Kit.</p></div><div class="offer-content"><img src="/book/the-long-game/pages/001.jpg" width="893" height="1263" alt="The Long Game book cover" loading="lazy"><div><h3>Choose the support that fits your routine.</h3><ul><li>The Long Game book and the Blueprint in every package.</li><li>Private Long Game Room access in every package.</li><li>VIP adds monthly group Q&amp;A and The Week Ahead.</li><li>Very VIP adds priority questions and early access to new material.</li></ul><a class="button premium-button" href="/premium/#premium-details">See packages and what’s included →</a><p class="meta">From $9 one-time. Materials and room access follow the payment-confirmation steps. Buying a Kit does not unlock articles on this website automatically.</p></div></div></section>'''
    articles=[
      ('preparing-gold-for-inflation-data','Event preparation','Preparing gold scenarios around inflation data','/assets/hero/how-inflation-affects-the-price-of-gold.png','Inflation headlines matter through expectations, rates and the dollar. Use a scenario map to separate those channels before considering an entry.',[
        ('Start with the question, not the direction','What would this release change about the market’s expected path for policy? Separate the headline and core measures, the monthly and annual comparisons, and any revisions. A bigger number is not a complete trading instruction: its surprise relative to expectations and the broader backdrop both matter.'),
        ('Build three conditional scenarios','For a stronger-than-expected release, observe whether yields and the dollar actually confirm a restrictive-policy interpretation. For a weaker release, check whether the response persists beyond the first price spike. For an in-line release, consider whether positioning, revisions or the next scheduled event dominate instead. These are observation prompts; gold can react differently in each setting.'),
        ('Define the conditions for doing nothing','Record the release time and your chart timeframe. Decide which spread, liquidity or price behaviour would keep you out. A stop is an order instruction rather than a guarantee of the fill price. If the release changes the execution environment beyond what your process was tested for, observation may be the more consistent choice.'),
        ('Review what changed','After the event, compare your written scenarios with the actual sequence: the data, initial response, follow-through and eventual close. Record whether the reasoning was useful even if no trade qualified. Review the release from its official source rather than relying only on a headline.')],'/economic-calendar/','Open the economic calendar'),
      ('building-a-gold-watchlist','Scenario planning','A gold watchlist begins with invalidation','/assets/hero/how-to-read-golds-trend-and-market-structure.png','Turn a directional view into a plan you can review: context, trigger, invalidation and the conditions for standing aside.',[
        ('Give the higher timeframe one job','Describe the environment as a trend, range or transition under a rule you can explain. Mark the areas that would change that description. This is context, not permission to take every lower-timeframe move in the same direction.'),
        ('Separate an idea from an order','An idea describes a possibility. An order requires a defined trigger, quantity and exit logic. For a hypothetical long setup, write what must happen before entry and what would make the long thesis invalid. For a short setup, write the corresponding conditions independently rather than simply reversing a bullish narrative.'),
        ('Size after defining invalidation','With a hypothetical $50 budget, a $10 stop distance and 100 ounces per lot, the planned size before costs is 0.05 lots. If the stop distance doubles, the same budget supports half the quantity. Contract increments, fees and slippage must also be considered; do not move an invalidation level merely to permit larger size.'),
        ('Write an expiry for the idea','A setup can become irrelevant after a release, a session change or a structural break. Give the plan a review time and a condition that cancels it. A missed move is not a reason to keep an expired thesis alive.')],'/trading/trade-ideas/','Build your own scenario plan'),
      ('reviewing-the-trading-week','Weekly review method','Review the week without rewriting the story','/assets/hero/how-to-be-a-consistent-trader.png','A useful recap records what was known at the time, what happened and what the process needs to change.',[
        ('Reconstruct the sequence','List the week’s major releases and policy events, then connect them to observed price responses. Keep the initial reaction separate from the later move. A neat explanation written after the close may hide the uncertainty faced during the session.'),
        ('Review results in comparable units','Record net results after costs as well as the initial risk of each trade. A result divided by its initial planned risk gives an R multiple. This helps compare different position sizes, but it does not replace an account-level record of cash flows and drawdown.'),
        ('Separate process errors from normal losses','A valid setup can lose, and a rule-breaking trade can win. Review whether the entry conditions, size and exit followed the plan. Look for repeated behaviours such as entering before confirmation or increasing size after a loss. Do not infer an edge from a handful of outcomes.'),
        ('Choose one change you can evaluate','Write one concrete action for the next review period: for example, calculate size before every demo order or exclude one untested news window. Define how compliance will be measured. Keep the rest of the process stable enough to assess whether that change helped.')],'/tools/trade-journal/','Open the practice journal')
    ]
    # These are evergreen public guides, not invented dated market calls or paid articles.
    from pathlib import Path
    root=Path(__file__).resolve().parents[1]
    rows=''
    for slug,kind,title,img,intro,sections,url,label in articles:
        if not (root/img.lstrip('/')).exists():img='/assets/inside/inside-1-chart.jpg'
        rows+=f'<article class="analysis-row"><a href="/analysis/{slug}/"><img src="{img}" alt="" loading="lazy" width="640" height="420"></a><div><p class="analysis-meta">{esc(kind)} <span class="free-label">FREE GUIDE</span></p><h2><a href="/analysis/{slug}/">{esc(title)}</a></h2><p>{esc(intro)}</p><a class="read" href="/analysis/{slug}/">Read the guide →</a></div></article>'
        body=f'<p class="analysis-meta">Black Gold Market · {esc(kind)} · Evergreen educational guide</p><div class="analysis-layout"><article class="analysis-body"><aside class="analysis-notice"><strong>Prepare with a repeatable process.</strong><p>Explore the book, checklist and community in the Trader’s Kit. <a href="/premium/#premium-details">See what each package includes →</a></p></aside><img class="analysis-hero" src="{img}" alt="Educational gold trading illustration" width="640" height="420">'
        body+=''.join(f'<section><h2>{esc(h)}</h2><p>{esc(p)}</p></section>' for h,p in sections)
        body+=f'<p><a class="button secondary" href="{url}">{label} →</a></p><p class="meta">This is a free educational guide, not a current market call. Examples are hypothetical and do not promise an outcome.</p>'+offer()+'''</article><aside class="analysis-sidebar"><span class="premium-label">GO FURTHER</span><h2>The Sustainable Trader’s Kit</h2><p>The book, the Blueprint and a private community for putting a process into practice.</p><a href="/premium/">Compare the packages →</a><hr><h3>Prepare your session</h3><a href="/economic-calendar/">Economic calendar</a><a href="/tools/gold-position-size/">Gold position size</a><a href="/analysis/">All analysis guides</a></aside></div>'''
        page('/analysis/'+slug+'/',title,intro,body)
    page('/analysis/','Analysis & market preparation','Read original guides to event preparation, scenario planning and reviewing your trading process.', '<div class="analysis-layout"><div>'+rows+offer()+'''</div><aside class="analysis-sidebar"><span class="premium-label">VIP PACKAGE</span><h2>The Week Ahead</h2><p>The existing VIP package includes a weekly note on key zones and monthly group Q&amp;A with Raphael.</p><a class="button premium-button" href="/premium/#premium-details">Explore VIP benefits</a><p class="meta">Delivered through the existing Kit/community service. These public guides do not require a purchase.</p></aside></div>'''+quote)
    plans=[('General',9,'The book and the foundations.',['The Long Game book (PDF)','The Sustainable Trader’s Blueprint','Private Long Game Room access','Future book and Blueprint updates']),('VIP',29,'The Kit, with discussion and a weekly map.',['Everything in General','Monthly group Q&A with Raphael','The Week Ahead: weekly key-zone note','7-day refund under the existing offer']),('Very VIP',49,'The Kit and VIP support, with priority.',['Everything in VIP','Priority for questions in Q&A','First access to new chapters and lessons','7-day refund under the existing offer'])]
    pricing='<section id="premium-details" class="premium-details"><p class="eyebrow">CHOOSE YOUR PACKAGE</p><h2>One-time packages. A clear next step.</h2><div class="premium-plans">'
    for name,amount,desc,features in plans:
        pricing+=f'<article class="premium-plan {"featured" if name=="VIP" else ""}"><span class="premium-label">{name}</span><h3>{esc(desc)}</h3><p class="package-price">${amount}<span>one-time</span></p><ul>'+''.join('<li>'+esc(f)+'</li>' for f in features)+f'</ul><a class="button premium-button" href="/vip/#pay">Continue to payment · ${amount}</a><p class="meta">No recurring billing. Confirm your package and follow the payment instructions.</p></article>'
    pricing+='</div></section>'
    comparison='''<section class="premium-comparison"><h2>What is included?</h2><div class="table-scroll"><table><thead><tr><th scope="col">Resource or benefit</th><th scope="col">Free</th><th scope="col">General · $9</th><th scope="col">VIP · $29</th><th scope="col">Very VIP · $49</th></tr></thead><tbody>'''
    for feature,values in [('Public academy, quizzes and glossary',['Included']*4),('Public analysis guides and trading tools',['Included']*4),('The Long Game PDF and private room',['—','Included','Included','Included']),('Monthly Q&A and The Week Ahead',['—','—','Included','Included']),('Priority Q&A and early material access',['—','—','—','Included'])]:
        comparison+='<tr><th scope="row">'+feature+'</th>'+''.join('<td>'+x+'</td>' for x in values)+'</tr>'
    comparison+='</tbody></table></div></section>'
    body='''<section class="premium-intro"><div><span class="premium-label">THE SUSTAINABLE TRADER’S KIT</span><h2>Take the next step<br>with a clear process.</h2><p>Study the book, keep the checklist close and choose the level of community support that suits your routine.</p><a class="button premium-button" href="#premium-details">Compare packages →</a><p class="meta">General $9 · VIP $29 · Very VIP $49 · All one-time</p></div><img src="/book/the-long-game/pages/001.jpg" width="893" height="1263" alt="The Long Game book cover"></section>'''+pricing+comparison+'''<section class="premium-delivery"><h2>How payment and delivery work</h2><ol><li>Choose a package and open the existing payment page.</li><li>Follow its crypto-payment instructions and check the listed network and amount carefully.</li><li>Send your receipt using the Telegram confirmation route on that page. The team confirms payment and provides your materials and room access.</li></ol><p>There is no automatic website login or article unlock after payment. The package is fulfilled through the existing delivery process. For the full offer and refund details, read the <a href="/vip/">Trader’s Kit page</a>.</p></section><section class="premium-faq"><h2>Before you choose</h2><details><summary>Is this a monthly subscription?</summary><p>No. These are the existing one-time Black Gold Market packages, with no automatic renewal.</p></details><details><summary>Does purchasing unlock the free Analysis guides?</summary><p>The public Analysis guides are already free. Your purchase covers the materials and benefits listed in the chosen package; it does not create a website member account.</p></details><details><summary>Which payment methods are available?</summary><p>The existing payment page lists crypto options and the instructions for receipt confirmation. Card payments, Apple Pay and Google Pay are not offered by this page.</p></details><details><summary>Will the package guarantee trading profits?</summary><p>No. The materials and community are educational. Trading involves risk, and no return is promised.</p></details><details><summary>I already bought a package. How do I access it?</summary><p>Use the materials and room link supplied after confirmation. If you need help, return to the Telegram contact route on the <a href="/vip/#pay">existing payment page</a>.</p></details></section>'''+quote
    page('/premium/','Explore the Trader’s Kit','Compare the existing Black Gold Market packages, their benefits and how to receive your materials.',body)
